config/routes.rb
Rails.application.routes.draw do

  resources :languages
  resources :courses
  resources :educations
  resources :employs
  resources :skills
  root 'welcome#index'

  devise_for :users, controllers: { 
    users: "users"
    }

  resources :users

end

app/models/employ.rb
class Employ < ActiveRecord::Base

  belongs_to :user
  
end

app/controllers/employs_controller.rb
class EmploysController < ApplicationController
  before_action :set_employ, only: [:show, :edit, :update, :destroy]

  # GET /employs
  # GET /employs.json
  def index
    @employs = Employ.all
    authorize! :edit, @employ
  end

  # GET /employs/1
  # GET /employs/1.json
  def show
    authorize! :edit, @employ
  end

  # GET /employs/new
  def new
    @employ = Employ.new
  end

  # GET /employs/1/edit
  def edit
    authorize! :edit, @employ
  end

  # POST /employs
  # POST /employs.json
  def create
    @employ = Employ.new(employ_params)
    current_user.employs << @employ
    respond_to do |format|
      if @employ.save
        format.html { redirect_to current_user, notice: 'Employ was successfully created.' }
        format.json { render :show, status: :created, location: @employ }
      else
        format.html { render :new }
        format.json { render json: @employ.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employs/1
  # PATCH/PUT /employs/1.json
  def update
    respond_to do |format|
      if @employ.update(employ_params)
        format.html { redirect_to current_user, notice: 'Employ was successfully updated.' }
        format.json { render :show, status: :ok, location: @employ }
      else
        format.html { render :edit }
        format.json { render json: @employ.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employs/1
  # DELETE /employs/1.json
  def destroy
    @employ.destroy
    respond_to do |format|
      format.html { redirect_to current_user, notice: 'Employ was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employ
      @employ = Employ.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employ_params
      params.require(:employ).permit(:organization, :position, :responsibility, :date_start, :date_finish)
    end
end

app/helpers/employs_helper.rb
module EmploysHelper
end

app/views/employs/_form.html.erb
<%= form_for(@employ) do |f| %>
  <% if @employ.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employ.errors.count, "error") %> prohibited this employ from being saved:</h2>

      <ul>
      <% @employ.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :organization %><br>
    <%= f.text_field :organization %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :responsibility %><br>
    <%= f.text_area :responsibility %>
  </div>
  <div class="field">
    <%= f.label :date_start %><br>
    <%= f.date_select :date_start, :start_year => 1920, :end_year => Date.current.year %>
  </div>
  <div class="field">
    <%= f.label :date_finish %><br>
    <%= f.date_select :date_finish, :start_year => 1920, :end_year => Date.current.year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employs/edit.html.erb
<h1>Editing Employ</h1>

<%= render 'form' %>

<%= link_to 'Show', @employ %> |
<%= link_to 'Back', employs_path %>

app/views/employs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Employs</h1>

<table>
  <thead>
    <tr>
      <th>Organization</th>
      <th>Position</th>
      <th>Responsibility</th>
      <th>Date start</th>
      <th>Date finish</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employs.each do |employ| %>
      <tr>
        <td><%= employ.organization %></td>
        <td><%= employ.position %></td>
        <td><%= employ.responsibility %></td>
        <td><%= employ.date_start %></td>
        <td><%= employ.date_finish %></td>
        <td><%= link_to 'Show', employ %></td>
        <td><%= link_to 'Edit', edit_employ_path(employ) %></td>
        <td><%= link_to 'Destroy', employ, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employ', new_employ_path %>

app/views/employs/new.html.erb
<h1>New Employ</h1>

<%= render 'form' %>

<%= link_to 'Back', employs_path %>

app/views/employs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Organization:</strong>
  <%= @employ.organization %>
</p>

<p>
  <strong>Position:</strong>
  <%= @employ.position %>
</p>

<p>
  <strong>Responsibility:</strong>
  <%= @employ.responsibility %>
</p>

<p>
  <strong>Date start:</strong>
  <%= @employ.date_start %>
</p>

<p>
  <strong>Date finish:</strong>
  <%= @employ.date_finish %>
</p>

<%= link_to 'Edit', edit_employ_path(@employ) %> |
<%= link_to 'Back', employs_path %>