config/routes.rb
Rails.application.routes.draw do

  resources :languages
  resources :courses
  resources :educations
  resources :employs
  resources :skills
  root 'welcome#index'

  devise_for :users, controllers: { 
    users: "users"
    }

  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :image, styles: { large: "600x600#", medium: "300x300#", small: "150x150#", thumb: "50x50#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

 


  has_many :skills
  has_many :employs
  has_many :educations
  has_many :courses
  has_many :languages
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def show
    @skill = Skill.new
    @language = Language.new
  end

  def edit
    authorize! :edit, @user
  end

  def update
    authorize! :edit, @user
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :birthday, :phone, :skype, :git, :country, :city, :image)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/__show.html.erb
<div class="container-fluid bg-1 text-center">
  <h3>Who Am I?</h3>
  <%= image_tag @user.image.url(:medium), class: "img-circle" %>
  <h3>I'm a <%= @user.first_name %> <%= @user.last_name %></h3>
</div>

<div class="container-fluid bg-2">
  <h3 class="text-center">Skills</h3>
  <div class="container">
    <%= render partial: "skill" %>
  <% if can? :edit, @user %>
    <%= render partial: "skills/form" %>
  <% end %>
  </div>

  <h3 class="text-center">Employment History</h3>
  <div class="container">
    <%= render partial: "employ" %>
    <% if can? :edit, @user %>
      <%= link_to 'Add Work', new_employ_path, class: "btn btn-default btn-xs" %><br>
    <% end %>
  </div>

  <h3 class="text-center">Education</h3>
  <div class="container">
    <%= render partial: "education" %>
    <% if can? :edit, @user %>
      <%= link_to 'Add Education', new_education_path, class: "btn btn-default btn-xs" %><br>
    <% end %>
  </div>

  <h3 class="text-center">Courses and Certificates</h3>
  <div class="container">
    <%= render partial: "course" %>
    <% if can? :edit, @user %>
      <%= link_to 'Add Course', new_course_path, class: "btn btn-default btn-xs" %><br>
    <% end %>
  </div>

  <h3 class="text-center">Languages</h3>
  <div class="container">
    <%= render partial: "language" %>
    <% if can? :edit, @user %>
      <%= render partial: "languages/form" %>
    <% end %>
  </div>
</div>

<div class="container-fluid bg-3">
  <h3>How To Find Me?</h3>
  <p>Phone: <%= @user.phone %></p>
  <p>Email: <%= @user.email %></p>
  <p>Skype: <%= @user.skype %></p>
  <p>GitHub: <%= @user.git %></p>
</div>

app/views/users/_course.html.erb
<% @user.courses.each do |i| %>
  <dl class="dl-horizontal">
    <dt class="primary">Title</dt>
    <dd><%= i.title %></dd>
    <dt class="primary">Awarded</dt>
    <dd><%= i.award %></dd>
    <% if can? :update, i %>
      <dt class="primary">Action</dt>
      <dd><%= link_to "Edit", edit_course_path(i), class: 'btn btn-primary btn-xs' %>
      <%= link_to "Destroy", course_path(i), method: 'delete', data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-danger btn-xs' %></dd>
    <% end %>
  </dl>
<% end %>

app/views/users/_education.html.erb
<% @user.educations.each do |i| %>
  <dl class="dl-horizontal">
    <dt class="primary">Date</dt>
    <dd><%= i.date_start.strftime("%B  %Y") %> - <%= i.date_finish.strftime("%B  %Y") %></dd>
    <dt class="primary">Organisation</dt>
    <dd><%= i.organization %></dd>
    <dt class="primary">Qualification</dt>
    <dd><%= i.qualification %></dd>
    <dt class="primary">Major</dt>
    <dd><%= i.major %></dd>
    <dt class="primary">Other</dt>
    <dd><%= i.other %></dd>
    <% if can? :update, i %>
      <dt class="primary">Action</dt>
      <dd><%= link_to "Edit", edit_education_path(i), class: 'btn btn-primary btn-xs' %>
      <%= link_to "Destroy", education_path(i), method: 'delete', data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-danger btn-xs' %></dd>
    <% end %>
  </dl>
<% end %>

app/views/users/_employ.html.erb
<% @user.employs.each do |i| %>
  <dl class="dl-horizontal">
    <dt class="primary">Date</dt>
    <dd><%= i.date_start.strftime("%B  %Y") %> - <%= i.date_finish.strftime("%B  %Y") %></dd>
    <dt class="primary">Organisation</dt>
    <dd><%= i.organization %></dd>
    <dt class="primary">Position</dt>
    <dd><%= i.position %></dd>
    <dt class="primary">Responsibility</dt>
    <dd><%= i.responsibility %></dd>
    <% if can? :update, i %>
      <dt class="primary">Action</dt>
      <dd><%= link_to "Edit", edit_employ_path(i), class: 'btn btn-primary btn-xs' %>
      <%= link_to "Destroy", employ_path(i), method: 'delete', data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-danger btn-xs' %></dd>
    <% end %>
  </dl>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, html: { class: 'form-horizontal', multipart: true } do |f| %>
  <div class="form-group">
    <%= f.label :image, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.file_field :image, class: 'file_field' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :email, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :first_name, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :first_name, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :last_name, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :last_name, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :birthday, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.date_select(:birthday, start_year: 1940, end_year: Time.now.year) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :country, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :country, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :city, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :city, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :phone, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :skype, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :skype, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :git, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :git, class: 'text_field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, class: 'btn btn-custom' %>
      <%= link_to t('.cancel', default: t("helpers.links.cancel")),
                  user_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/users/_language.html.erb
<dl class="dl-horizontal riga">
<% @user.languages.each do |i| %>
  <dt class="primary"><%= i.name %></dt>
  <dd>
    <%= i.level %> 
    <% if can? :update, i %> 
      <%= link_to "Destroy", language_path(i), method: 'delete', data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'position_right' %>
    <% end %>   
  </dd>
<% end %>
</dl>

app/views/users/_skill.html.erb
<table class="table">
      <thead>
        <tr>
          <th>Technology</th>
          <th>Years of Experience</th>
          <th>Proficiency</th>
          <% if can? :edit, @user %>
            <th>Action</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
      <% @user.skills.each do |i| %>
        <tr>
          <td><%= i.technology %></td>
          <td><%= i.exp %></td>
          <td><%= i.proficiency %></td>
          <% if can? :update, i %>
            <td>
              <%= link_to "Edit", edit_skill_path(i), class: 'btn btn-primary btn-xs' %> <%= link_to "Destroy", skill_path(i), method: 'delete', data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-danger btn-xs' %>
            </td>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

app/views/users/show.html.erb
<div class="container-fluid bg-1">
  <br>
  <div class="row content">
    <div class="col-sm-3">
      <% if @user.image_file_name %>
        <%= image_tag @user.image.url(:large), class: "img-thumbnail" %>
      <% else %>
        <%= image_tag "ava.jpeg", size: "300", class: "img-thumbnail" %>
      <% end %>
      <hr>
      <ul class="nav nav-pills nav-stacked panel">
        <li><a href="#skills">Skills</a></li>
        <li><a href="#employ">Employment History</a></li>
        <li><a href="#education">Education</a></li>
        <li><a href="#courses">Courses and certificates</a></li>
        <li><a href="#languages">Languages</a></li>
      </ul>
    </div>

    <div class="col-sm-9" id="name">
        <div class="panel-group">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4 class="panel-title">
                <h3><%= @user.first_name %> <%= @user.last_name %>
                  <% if can? :edit, @user %>
                    <small> <%= link_to "Edit", edit_user_path %></small>
                  <% end %>
                </h3>
                <hr>
                <dl class="dl-horizontal">
                  <dt class="primary">Birthday</dt>
                  <dd><%= @user.birthday.strftime("%d  %B  %Y") if @user.birthday %></dd>
                  <dt class="primary">City</dt>
                  <dd><%= @user.city %></dd>
                </dl>
                <a data-toggle="collapse" href="#collapse1">More information</a>
              </h4>
            </div>
            <div id="collapse1" class="panel-collapse collapse">
              <div class="container-fluid">
                <dl class="dl-horizontal">
                  <dt class="primary">Email</dt>
                  <dd><%= @user.email %></dd>
                  <dt class="primary">Phone</dt>
                  <dd>(<%= @user.phone.delete(" ")[0..2] if @user.phone %>) <%= @user.phone.delete(" ")[3..99] if @user.phone %></dd>
                  <dt class="primary">Skype</dt>
                  <dd><%= @user.skype %></dd>
                  <dt class="primary">Git</dt>
                  <dd><%= @user.git %></dd>
                </dl>
                <dl class="dl-horizontal">
                  <dt class="primary">Country</dt>
                  <dd><%= @user.country %></dd>
                  <dt class="primary">City</dt>
                  <dd><%= @user.city %></dd>
                </dl>
              </div>
            </div>

          </div>
          <div class="panel panel-default white" id="skills">
            <h3 class="text-center">Skills</h3>
            <%= render partial: "skill" %>
            <% if can? :edit, @user %>
              <%= render partial: "skills/form" %>
            <% end %>
          </div>
          <div class="panel white" id="employ">
            <h3 class="text-center">Employment History</h3>
            <%= render partial: "employ" %>
            <% if can? :edit, @user %>
              <%= link_to 'Add Work', new_employ_path, class: "btn btn-default btn-xs" %><br>
            <% end %>
          </div>
          <div class="panel white" id="education">
            <h3 class="text-center">Education</h3>
            <%= render partial: "education" %>
            <% if can? :edit, @user %>
              <%= link_to 'Add Education', new_education_path, class: "btn btn-default btn-xs" %><br>
            <% end %>
          </div>
          <div class="panel white" id="courses">
            <h3 class="text-center">Courses and Certificates</h3>
            <%= render partial: "course" %>
            <% if can? :edit, @user %>
              <%= link_to 'Add Course', new_course_path, class: "btn btn-default btn-xs" %><br>
            <% end %>
          </div>
          <div class="panel white" id="languages">
            <h3 class="text-center">Languages</h3>
            <%= render partial: "language" %>
            <% if can? :edit, @user %>
              <%= render partial: "languages/form" %>
            <% end %>
          </div>
      </div>
    </div>

  </div>
</div>