config/routes.rb
Rails.application.routes.draw do

  resources :languages
  resources :courses
  resources :educations
  resources :employs
  resources :skills
  root 'welcome#index'

  devise_for :users, controllers: { 
    users: "users"
    }

  resources :users

end

app/models/education.rb
class Education < ActiveRecord::Base

  belongs_to :user
  
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  before_action :set_education, only: [:show, :edit, :update, :destroy]

  # GET /educations
  # GET /educations.json
  def index
    @educations = Education.all
    authorize! :edit, @education
  end

  # GET /educations/1
  # GET /educations/1.json
  def show
    authorize! :edit, @education
  end

  # GET /educations/new
  def new
    @education = Education.new
  end

  # GET /educations/1/edit
  def edit
    authorize! :edit, @education
  end

  # POST /educations
  # POST /educations.json
  def create
    @education = Education.new(education_params)
    current_user.educations << @education
    respond_to do |format|
      if @education.save
        format.html { redirect_to current_user, notice: 'Education was successfully created.' }
        format.json { render :show, status: :created, location: @education }
      else
        format.html { render :new }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /educations/1
  # PATCH/PUT /educations/1.json
  def update
    respond_to do |format|
      if @education.update(education_params)
        format.html { redirect_to current_user, notice: 'Education was successfully updated.' }
        format.json { render :show, status: :ok, location: @education }
      else
        format.html { render :edit }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /educations/1
  # DELETE /educations/1.json
  def destroy
    @education.destroy
    respond_to do |format|
      format.html { redirect_to current_user, notice: 'Education was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_education
      @education = Education.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def education_params
      params.require(:education).permit(:organization, :qualification, :major, :other, :date_start, :date_finish)
    end
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/views/educations/_form.html.erb
<%= form_for(@education) do |f| %>
  <% if @education.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@education.errors.count, "error") %> prohibited this education from being saved:</h2>

      <ul>
      <% @education.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :organization %><br>
    <%= f.text_field :organization %>
  </div>
  <div class="field">
    <%= f.label :qualification %><br>
    <%= f.text_field :qualification %>
  </div>
  <div class="field">
    <%= f.label :major %><br>
    <%= f.text_field :major %>
  </div>
  <div class="field">
    <%= f.label :other %><br>
    <%= f.text_area :other %>
  </div>
  <div class="field">
    <%= f.label :date_start %><br>
    <%= f.date_select :date_start, :start_year => 1920, :end_year => Date.current.year %>
  </div>
  <div class="field">
    <%= f.label :date_finish %><br>
    <%= f.date_select :date_finish, :start_year => 1920, :end_year => Date.current.year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/educations/edit.html.erb
<h1>Editing Education</h1>

<%= render 'form' %>

<%= link_to 'Show', @education %> |
<%= link_to 'Back', educations_path %>

app/views/educations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Educations</h1>

<table>
  <thead>
    <tr>
      <th>Organization</th>
      <th>Qualification</th>
      <th>Major</th>
      <th>Other</th>
      <th>Date start</th>
      <th>Date finish</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @educations.each do |education| %>
      <tr>
        <td><%= education.organization %></td>
        <td><%= education.qualification %></td>
        <td><%= education.major %></td>
        <td><%= education.other %></td>
        <td><%= education.date_start %></td>
        <td><%= education.date_finish %></td>
        <td><%= link_to 'Show', education %></td>
        <td><%= link_to 'Edit', edit_education_path(education) %></td>
        <td><%= link_to 'Destroy', education, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Education', new_education_path %>

app/views/educations/new.html.erb
<h1>New Education</h1>

<%= render 'form' %>

<%= link_to 'Back', educations_path %>

app/views/educations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Organization:</strong>
  <%= @education.organization %>
</p>

<p>
  <strong>Qualification:</strong>
  <%= @education.qualification %>
</p>

<p>
  <strong>Major:</strong>
  <%= @education.major %>
</p>

<p>
  <strong>Other:</strong>
  <%= @education.other %>
</p>

<p>
  <strong>Date start:</strong>
  <%= @education.date_start %>
</p>

<p>
  <strong>Date finish:</strong>
  <%= @education.date_finish %>
</p>

<%= link_to 'Edit', edit_education_path(@education) %> |
<%= link_to 'Back', educations_path %>